# Generated by Django 4.2.20 on 2026-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_file_type_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracted', 'Extracted'), ('processing', 'Processing'), ('processed', 'Processed'), ('validated', 'Validated'), ('error', 'Error')], default='uploaded', max_length=20),
        ),
    ]
