declare module 'react-icons/fi' {
  import { ComponentType, SVGAttributes } from 'react';
  export interface IconBaseProps extends SVGAttributes<SVGElement> {
    size?: string | number;
    color?: string;
    title?: string;
  }
  export type IconType = ComponentType<IconBaseProps>;
  export const FiActivity: IconType;
  export const FiAlertCircle: IconType;
  export const FiAlertTriangle: IconType;
  export const FiArrowLeft: IconType;
  export const FiArrowRight: IconType;
  export const FiArrowUp: IconType;
  export const FiArrowDown: IconType;
  export const FiBarChart2: IconType;
  export const FiBook: IconType;
  export const FiBookOpen: IconType;
  export const FiCheck: IconType;
  export const FiCheckCircle: IconType;
  export const FiChevronDown: IconType;
  export const FiChevronUp: IconType;
  export const FiChevronLeft: IconType;
  export const FiChevronRight: IconType;
  export const FiClock: IconType;
  export const FiCode: IconType;
  export const FiCopy: IconType;
  export const FiCpu: IconType;
  export const FiDatabase: IconType;
  export const FiDownload: IconType;
  export const FiEdit: IconType;
  export const FiExternalLink: IconType;
  export const FiEye: IconType;
  export const FiFile: IconType;
  export const FiFileText: IconType;
  export const FiFilter: IconType;
  export const FiGithub: IconType;
  export const FiGlobe: IconType;
  export const FiGrid: IconType;
  export const FiHash: IconType;
  export const FiHelpCircle: IconType;
  export const FiHome: IconType;
  export const FiInfo: IconType;
  export const FiLayers: IconType;
  export const FiList: IconType;
  export const FiLoader: IconType;
  export const FiLock: IconType;
  export const FiMail: IconType;
  export const FiMaximize: IconType;
  export const FiMenu: IconType;
  export const FiMinimize: IconType;
  export const FiMinus: IconType;
  export const FiMoreVertical: IconType;
  export const FiPaperclip: IconType;
  export const FiPlus: IconType;
  export const FiRefreshCw: IconType;
  export const FiRepeat: IconType;
  export const FiSearch: IconType;
  export const FiSettings: IconType;
  export const FiShare: IconType;
  export const FiShield: IconType;
  export const FiStar: IconType;
  export const FiTable: IconType;
  export const FiTrash: IconType;
  export const FiTrash2: IconType;
  export const FiTrendingUp: IconType;
  export const FiUnlock: IconType;
  export const FiUpload: IconType;
  export const FiUploadCloud: IconType;
  export const FiUser: IconType;
  export const FiUsers: IconType;
  export const FiX: IconType;
  export const FiXCircle: IconType;
  export const FiZap: IconType;
}
